### ISSUE TITLE
TiddlyFox has not been updated to Firefox 42.0

### ISSUE THREAD

**Issue by kyanha** [TiddlyWiki/TiddlyFox#34]
The reference on tiddlywiki.com for Android specifies to get the latest version of Firefox, which at the time of this writing is 42.0.  I have installed it.

I also installed Save Link Menus (out of order, I know, but it looked interesting enough that I wanted it anyway).

I then attempted to install TiddlyFox from addons.mozilla.org.  The site states that it has not been updated to Firefox 42.0, and refuses to permit installation.

When is the next release to AMO (to support FF 42) expected?  I would very much like to be able to use TiddlyWiki on my phone.

Thank you very much for creating and maintaining this -- it has been awesome on my main system, and having the ability to use it on my phone will be amazing.

**Comment by Jermolene** [comment]
Hi @kyanha I've updated the version information for TiddlyFox. Please give it another try, and let me know how you get on.

**Comment by kyanha** [comment]
It now works, and works well!  Thanks. :100:
