### ISSUE TITLE
TiddlyFox is disabled by force in FF 43

### ISSUE THREAD

**Issue by felixhayashi** [TiddlyWiki/TiddlyFox#36]
Hi @Jermolene 

after installing FF 43 TiddlyFox (v2) doesn't work anymore :(

![2015-12-20 12 07 24](https://cloud.githubusercontent.com/assets/4307137/11917701/692aa2ba-a712-11e5-80ad-f15f02646e2e.png)

Would be great if you could fix it. Many Thanks!

-Felix

**Comment by Jermolene** [comment]
Hi @felixhayashi my bad, I'm afraid.

I've abandoned the v2 branch of TiddlyFox because the underlying SDK doesn't work in Firefox for Android. Once 5.1.10 is out, I do plan to revise TiddlyFox, but I'll be updating the version that you see in AMO at the moment. It works OK in Firefox 43.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

thanks for the prompt response!

> I've abandoned the v2 branch of TiddlyFox because the underlying SDK doesn't work in Firefox for Android.

Ah ok, get it.

> Once 5.1.10 is out, I do plan to revise TiddlyFox, but I'll be updating the version that you see in AMO at the moment. It works OK in Firefox 43.

Great! I am not familiar with what AMO stands for (google spits out stuff like Atlantic Multi-decadal Oscillation, Aviation Medical Officer,…). Sorry, it appears that my internet speak is quite underdeveloped.

**Comment by Jermolene** [comment]
Sorry @felixhayashi AMO is "http://addons.mozilla.org"; as usual, obvious when you know :)

**Comment by felixhayashi** [comment]
Hi @Jermolene 

> Sorry @felixhayashi AMO is "http://addons.mozilla.org"; as usual, obvious when you know :)

Would have never guessed that!!
Ok, then I guess I'll revert to v1 that is available in AMO for now.

-Felix
