### ISSUE TITLE
In Firefox 45 on Linux "the add-on could not be verified for use in Firefox and has been disabled."

### ISSUE THREAD

**Issue by uboubo** [TiddlyWiki/TiddlyFox#40]
So it's more a Firefox-issue, but a problem, that TiddlyFox cannot be used any more.

**Comment by uboubo** [comment]
Sorry, I am feeling very stupid now!
Removing and new installation of TiddlyFox solved my problem.
Sorry again!

**Comment by Jermolene** [comment]
Great @uboubo, glad you're up and running
