### ISSUE TITLE
Firefox developers need examples of extensions which require direct filesystem access

### ISSUE THREAD

**Issue by ssokolow** [TiddlyWiki/TiddlyFox#42]
Yesterday, this was posted to the Bugzilla [feature request](https://bugzilla.mozilla.org/show_bug.cgi?id=1246236) for an API to allow direct filesystem access from WebExtensions (which Mozilla intends to aggressively replace earlier extension types with over the course of 2017):

> At this time we think it makes sense to:
> 
> * implement a streaming API for downloads, this is basically the proposal on bug 1323414 and would allow add-ons that stream a large amount of data (for example Video Download Helper) to be ported over to WebExtensions. More bugs will be filed for this.
> 
> * bug 1331618 allows extensions to store up to 20gb per file into indexeddb and use that as a virtual file system and should meet most storage systems. We might need to add in a library to make this easier to use, or re-use one that already exists.
> 
> Most use cases we've found so far would fit into one of the two use cases above. So for the moment **I'm dropping this down until we can find more use cases**.

Emphasis mine. The streaming API mentioned is basically an extension to the Chrome downloads API and doesn't allow targeting arbitrary paths or renaming existing files to add a `.backup`.

**Comment by tfeb** [comment]
This is a really major issue: if Tiddlyfox

**Comment by Jermolene** [comment]
Thanks for the heads up @ssokolow; it is tremendously helpful that you are engaged with Mozilla. I'm working on a response to the bug thread, and then perhaps it would be helpful to bring this up in the main TiddlyWiki group, and encourage people to add their own thoughts to the thread?

**Comment by ssokolow** [comment]
I'm no expert, but that sounds reasonable. (I'm just subscribed to Planet Mozilla and have been been keeping a close eye on the WebExtensions effort.)

**Comment by ssokolow** [comment]
Given the general tone of the conversation, I'm starting to worry that TiddlyFox will have to use either [nativeMessaging](https://developer.chrome.com/extensions/nativeMessaging) or a completely standalone "reinvent XULConnect as a localhost HTTP server" binary.

Either way, I suppose the simplest solution would be to brush up on using Rust to cross-compile a ton of different 100% statically-linked native binaries from the same "simple HTTP server" source code.

**Comment by tfeb** [comment]
This terrifies me.  TiddlyWiki has been how I run my life for more than ten years: I think I have something between a million and five million words of notes in TW (I have something like 130,000 in my current work TW which is just under two years old, I don't have the tools to easily count all my TW2 instances).  And the *whole thing* that made this possible was that TW is this lovely thing which will work, basically, anywhere: you don't need some vast stack of software to keep it working, and it will work places where you essentially *can't* install SW.  I'm not even sure why I would keep using Firefox if all that breaks (I *certainly* would switch to another browser if it worked with TW and FF didn't).

**Comment by ssokolow** [comment]
I'm in the same situation on almost every point you make, and my data is in TWc so, worst case scenario, I'll do my best to come up with an alternative to locking down an old version of Firefox and keeping it around.

(In fact, just today, I started a [serious plan](https://gist.github.com/ssokolow/2fb8debc7dfdbf1d9a0da90284f5d73a) to evaluate whether I should migrate off Firefox as a result of this.)

Regarding TiddlyWiki, as I mentioned, if they don't provide APIs for TiddlyFox, I'll probably write an HTTP server and saver for TiddlyWiki where the server is a single, small executable binary with no dependencies and then cross-compile it for 32-bit Linux, Windows XP, OSX, and whatever BSDs I can easily set up a cross-compiler for.

**Comment by tfeb** [comment]
There's now somewhere around three months before Firefox 57: is there any hope for a painless TW system after that point?  Does anyone have any *painless* (I do not want to have to run a server since I need to use the same TW in multiple locations) lifeboat?

**Comment by ssokolow** [comment]
It depends on why you don't want to run a server. If you don't need to use it on machines which restrict which applications you can run, you could carry around either a pre-57 copy of [Portable Firefox](https://portableapps.com/apps/internet/firefox_portable) or a portable copy of Node.js on a thumbdrive.

(A quick Google turned up at least four different ways to run Node.js in a portable configuration.)

Then, all you'd need is a quick little `.cmd` file which automates the process of pulling it up, so it's still just one double-click.

In the longer term, if nobody here comes up with a solution, I'll probably whip up a Rust-based, statically-linked HTTP server to provide a backend for TiddlyFox which I can compile for Linux, Windows, and OSX and carry around alongside the wiki as a successor to `TiddlySaver.jar`.

**Comment by pmario** [comment]
Hi, I think this one can be closed. 

a) The FF devs made clear, what they are willing to implement. As in "no more comments allowed" in:https://bugzilla.mozilla.org/show_bug.cgi?id=1246236 and the wiki: https://wiki.mozilla.org/WebExtensions/Filesystem

b) We do have 2 web extensions atm, that can write to the downloads folder, which is configured in the browser settings. 

See: https://groups.google.com/forum/#!topic/tiddlywiki/h0k7z62N79Y
and: https://groups.google.com/forum/#!topic/tiddlywiki/9984ShVVbbA

**Comment by pmario** [comment]
I think this is interesting too: https://groups.google.com/d/msg/tiddlywiki/h0k7z62N79Y/mOnErEHqBwAJ

**Comment by Jermolene** [comment]
Hi @ssokolow @pmario yes, it seems that this boat has sailed.

**Comment by tfeb** [comment]
I think this can be closed as well.  I've realised that telling Firefox to not ask where to download HTML files to, combined with my existing little 'check for copies in `~/Downloads`, copy and commit every 60 seconds` script does most of what I need (in particular it means that you don't get some annoying dialog box every time you need to save something).

**Comment by ssokolow** [comment]
> telling Firefox to not ask where to download HTML files to

I consider that an unacceptable harm to my workflow for other downloads. As someone with JS experience but no TiddlyWiki/TiddlyFox internals experience, what reference URLs should I start at in order to write a TiddlyFox successor which monkey-patches TWc to save via a custom ReST->Filesystem daemon?

(At the moment, I have more pressing concerns, since Firefox 52ESR will be supported for several months after my web host raises the rates on some of my projects, but I'll add this to my list of TODOs that need to be completed before I'm wiling to allow Firefox to upgrade beyond 52ESR.)

**Comment by tfeb** [comment]
> I consider that an unacceptable harm to my workflow for other downloads

Worth noting perhaps that it only affects *HTML* downloads (ie it still asks you what to do with any other kind).  I almost never download HTML files, so it didn't hurt me much.  It's still a pain.

**Comment by ssokolow** [comment]
While I was unaware of that, it's still not enough, given that, when I read fanfiction from various sites, I manually download the "export as HTML" for each chapter into a sorted archive folder as I read it.

...and I rely heavily on Firefox's ability to remember a different "last download folder" for each domain, so I can't just solve it the same way I plan to work around the race condition which has been periodically livelocking Chromium in the Save dialog on my system for the last few Chromium releases. (A livelock has the outward appearance of a deadlock, but it pegs one CPU core at 100%.)

(My planned workaround for that is to set Chromium's download folder to `~/.unsorted_downloads` with no save dialog popup, identify whether it's `IN_CLOSE_WRITE` or `IN_MOVED_TO` that signals Chrome is done with the file, and then write an inotify-based monitor which pops up a save dialog external to the browser.)
