### ISSUE TITLE
Unable to save an updated document

### ISSUE THREAD

**Issue by seokbeomKim** [TiddlyWiki/TiddlyFox#47]
After upgrading firefox to 52.0.2 (32bits), it is not able to save wiki page automatically which has been supported by the TiddlyFox addons.

**Comment by Jermolene** [comment]
Hi @seokbeomKim have you upgraded to the latest version 2.0.1 of TiddlyFox?

https://addons.mozilla.org/en-us/firefox/addon/tiddlyfox/versions/

**Comment by seokbeomKim** [comment]
Problem has been solved.
Thanks a lot!
